// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvnEKfIqgoqpv8ghhXPNNX99Y9mzRDuJs',
    appId: '1:1048891053119:web:8677ec693980636fc2548a',
    messagingSenderId: '1048891053119',
    projectId: 'todo1-1d499',
    authDomain: 'todo1-1d499.firebaseapp.com',
    storageBucket: 'todo1-1d499.appspot.com',
    measurementId: 'G-8QKYLSZE6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKzkO_Els2NXd-usmYo5GOFDykeASqQa4',
    appId: '1:1048891053119:android:f923967d313cca7dc2548a',
    messagingSenderId: '1048891053119',
    projectId: 'todo1-1d499',
    storageBucket: 'todo1-1d499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxmsRcuPmj_BwSglGBmcfQK7AlxO5kLbA',
    appId: '1:1048891053119:ios:a1e71cfe57bb2bf9c2548a',
    messagingSenderId: '1048891053119',
    projectId: 'todo1-1d499',
    storageBucket: 'todo1-1d499.appspot.com',
    iosClientId: '1048891053119-dvtr02qposcd29d9k5ru3ijth1k91fo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxmsRcuPmj_BwSglGBmcfQK7AlxO5kLbA',
    appId: '1:1048891053119:ios:44e89e65abf39109c2548a',
    messagingSenderId: '1048891053119',
    projectId: 'todo1-1d499',
    storageBucket: 'todo1-1d499.appspot.com',
    iosClientId: '1048891053119-7fgambfh9hkr159cqb42345u1jv5fiv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
